CREATE TABLE IF NOT EXISTS posts (
    id UUID PRIMARY KEY,
    content TEXT NOT NULL,
    author TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE,
    origin_node TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS nodes (
    id TEXT PRIMARY KEY,
    url TEXT NOT NULL,
    last_seen TIMESTAMP WITH TIME ZONE NOT NULL
);
